# Generated by Django 4.0 on 2022-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_remove_profile_follower_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='post_text',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
